MyPortfolio_MVC/Controllers/AdminLayoutController.cs
using MyPortfolio_MVC.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolio_MVC.Controllers
{

    
    public class AdminLayoutController : Controller
    {
        MyPortfolioEntities db = new MyPortfolioEntities(); 
        public ActionResult Layout()   
        {
            return View();
        }

        public PartialViewResult AdminLayoutHead()
        {
            return PartialView();
        }

        public PartialViewResult AdminLayoutSpinner()
        {
            return PartialView();
        }

        public PartialViewResult AdminLayoutSidebar()
        {
            var Email = Session["email"].ToString();
            var admin = db.TblAdmins.FirstOrDefault(x =>x.Email == Email);

            ViewBag.nameSurname = admin.Name + " " + admin.Surname;
            ViewBag.image = admin.ImageUrl;
            return PartialView();
        }
        public PartialViewResult AdminLayoutNavbar()
        {
            var Email = Session["email"].ToString();
            var admin = db.TblAdmins.FirstOrDefault(x => x.Email == Email);

            ViewBag.nameSurname=admin.Name + " " + admin.Surname;
            ViewBag.image = admin.ImageUrl;
            return PartialView();
             
        }
        
        public PartialViewResult  AdminLayoutFooter()

        {
            return PartialView();
        }

        public PartialViewResult AdminLayoutScripts()

        {
            return PartialView();
        }
    }

}

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutFooter.cshtml
 
<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded-top p-4">
        <div class="row">
            <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="#">My Portfolyo</a>, Tüm Hakları Saklıdır.
            </div>
            <div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </div>
        </div>
    </div>
</div>

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutHead.cshtml
<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Templates/darkpan-1.0.0/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/Templates/darkpan-1.0.0/css/style.css" rel="stylesheet">
</head>

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutNavbar.cshtml
<nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
    <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
    </a>
    <a href="#" class="sidebar-toggler flex-shrink-0">
        <i class="fa fa-bars"></i>
    </a>
    <form class="d-none d-md-flex ms-4">
        <input class="form-control bg-dark border-0" type="search" placeholder="Ara..">
    </form>
    <div class="navbar-nav align-items-center ms-auto">
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-envelope me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Mesajlar</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all message</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-bell me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Notificatin</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Profile updated</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">New user added</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Password changed</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all notifications</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img class="rounded-circle me-lg-2" src="@ViewBag.image" alt="" style="width: 40px; height: 40px;">
                <span class="d-none d-lg-inline-flex">@ViewBag.nameSurname</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">Siteye Git</a>
                <a href="/Profile/Index" class="dropdown-item">Profilime Git</a>
                <a href="#" class="dropdown-item">Çıkış Yap</a>
            </div>
        </div>
    </div>
</nav>

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutScripts.cshtml
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/chart/chart.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/easing/easing.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/waypoints/waypoints.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/Templates/darkpan-1.0.0/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Template Javascript -->
<script src="~/Templates/darkpan-1.0.0/js/main.js"></script>

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutSidebar.cshtml
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-secondary navbar-dark">
        <a href="index.html" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>MyPortFolio</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="@ViewBag.image" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">@ViewBag.nameSurname</h6>
                <span>Admin</span>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="/Default/index" class="nav-item nav-link"><i class=" fa fa-laptop me-0-2"></i>Siteye Git </a>/>
                

                <a href="/Profile/index" class="nav-item nav-link"><i class="fa fa-user-edit me-2"></i> Profil Bilgileri</a>

                <a href="/Category/index" class="nav-item nav-link"><i class="fa fa-list me-2"></i> Kategoriler</a>
                <a href="/Project/index" class="nav-item nav-link"><i class="fa fa-asterisk me-2"></i> Projelerim</a>
                <a href="/About/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Hakkımda</a>
                <a href="/Banner/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Banner</a>
                <a href="/Contact/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> İletişim</a>
                <a href="/Education/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Eğitim</a>
                <a href="/Experience/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Deneyim</a>
                <a href="/Expertise/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Uzmanlık Alanın</a>
                <a href="/Message/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Gelen Mesajlar</a>
                <a href="/SocialMedia/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Sosyal Medya</a>
                <a href="/Testimonial/index" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> Refereanslar</a>

</div>
    </nav>
</div>

MyPortfolio_MVC/Views/AdminLayout/AdminLayoutSpinner.cshtml
<div id="spinner" class="show bg-info position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

MyPortfolio_MVC/Views/AdminLayout/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@*@Html.Partial("~/Views/AdminLayout/AdminLayoutHead.cshtml")*@
@Html.Action("AdminLayoutHead", "AdminLayout")

<body>
    <div class="container-fluid position-relative d-flex p-0">
        @Html.Action("AdminLayoutSpinner", "AdminLayout")
       
       
        @Html.Action("AdminLayoutSidebar", "AdminLayout")
       
        <div class="content">
          
            @Html.Action("AdminLayoutNavbar", "AdminLayout")
           
            <div class="container-fluid pt-4 px-4">
               
                <div class="col-12 bg-secondary">
                
                    @RenderBody()
               
                </div>
            
            </div>
           
            @Html.Action("AdminLayoutFooter", "AdminLayout")
       
        </div>
        
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    
    @Html.Action("AdminLayoutScripts", "AdminLayout")

</body>

</html>